package remindergui;

import com.github.lgooddatepicker.components.DatePickerSettings;
import com.github.lgooddatepicker.components.TimePickerSettings;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class ReminderJFrame extends javax.swing.JFrame {

    private static ReminderJFrame instance = null;
    public static ArrayList<Reminder> remindArray = new ArrayList<>();
    /**
     * Creates new form ReminderJFrame
     */
    private ReminderJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogEventReminder = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaMessage = new javax.swing.JTextArea();
        jButtonDismiss = new javax.swing.JButton();
        DatePickerSettings dateSettings = new DatePickerSettings();
        dateSettings.setAllowEmptyDates(false);
        TimePickerSettings timeSettings = new TimePickerSettings();
        timeSettings.setAllowEmptyTimes(false);
        timeSettings.setDisplaySpinnerButtons(true);
        timeSettings.setInitialTimeToNow();
        dateTimePickerReminder = new com.github.lgooddatepicker.components.DateTimePicker(dateSettings, timeSettings);
        jLabelNewReminder = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaNewMessage = new javax.swing.JTextArea();
        jLabelNewMessage = new javax.swing.JLabel();
        jButtonAdd = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jLabelSavedReminders = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListReminders = new javax.swing.JList<>();

        jDialogEventReminder.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialogEventReminder.setAlwaysOnTop(true);

        jLabel1.setText("Reminder:");

        jTextAreaMessage.setColumns(20);
        jTextAreaMessage.setRows(5);
        jTextAreaMessage.setEditable(false);
        jScrollPane3.setViewportView(jTextAreaMessage);

        jButtonDismiss.setText("Dismiss");
        jButtonDismiss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDismissActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogEventReminderLayout = new javax.swing.GroupLayout(jDialogEventReminder.getContentPane());
        jDialogEventReminder.getContentPane().setLayout(jDialogEventReminderLayout);
        jDialogEventReminderLayout.setHorizontalGroup(
            jDialogEventReminderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEventReminderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogEventReminderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogEventReminderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonDismiss)
                .addContainerGap())
        );
        jDialogEventReminderLayout.setVerticalGroup(
            jDialogEventReminderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEventReminderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDismiss)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reminder App");

        jLabelNewReminder.setText("New reminder:");

        jTextAreaNewMessage.setColumns(20);
        jTextAreaNewMessage.setRows(5);
        jTextAreaNewMessage.setToolTipText("Write the message you want to see with your reminder here.");
        jScrollPane1.setViewportView(jTextAreaNewMessage);

        jLabelNewMessage.setText("Message:");

        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jLabelSavedReminders.setText("Saved reminders:");

        jListReminders.setModel(new DefaultListModel<String>());
        jScrollPane2.setViewportView(jListReminders);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNewMessage)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonAdd)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(dateTimePickerReminder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNewReminder, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(297, 297, 297)
                                .addComponent(jButtonDelete))
                            .addComponent(jLabelSavedReminders))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNewReminder)
                    .addComponent(jLabelSavedReminders))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dateTimePickerReminder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabelNewMessage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd)
                    .addComponent(jButtonDelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        String dateString = dateTimePickerReminder.toString();
        String msg = jTextAreaNewMessage.getText();
        Reminder tempReminder = new Reminder(dateString, msg);
        remindArray.add(tempReminder);
        ((DefaultListModel)jListReminders.getModel()).addElement(tempReminder.toString());
        jTextAreaNewMessage.setText("");
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        remindArray.remove(jListReminders.getSelectedIndex());
        ((DefaultListModel)jListReminders.getModel()).removeElementAt(jListReminders.getSelectedIndex());       
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonDismissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDismissActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDismissActionPerformed

    public static ReminderJFrame getInstance() {
        if (instance == null) {
            instance = new ReminderJFrame();
        }
        return instance;
    }
    
    // Creates a new Option pane in a new thread
    public static void matchFound(String msg, int idx) {
        Thread t = new Thread(new Runnable(){
            @Override
            public void run(){
                JOptionPane.showMessageDialog(null, msg);
            }
        });
        t.start();    
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.lgooddatepicker.components.DateTimePicker dateTimePickerReminder;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonDismiss;
    private javax.swing.JDialog jDialogEventReminder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelNewMessage;
    private javax.swing.JLabel jLabelNewReminder;
    private javax.swing.JLabel jLabelSavedReminders;
    public static javax.swing.JList<String> jListReminders;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaMessage;
    private javax.swing.JTextArea jTextAreaNewMessage;
    // End of variables declaration//GEN-END:variables
}
