package remotecommand;

import javax.swing.JTextArea;

/**
 *
 * @author Jere Kaplas, 0403105, LUT
 */
// Using Remote directly as the main class for this simple enough example, as seperating the Mainclass doesn't really have a benefit here.
public class Remote extends javax.swing.JFrame {
    
    // The remote can hold three commands
    private static Command slot1;
    private static Command slot2;
    private static Command slot3;
    
    /**
     * Creates new form Remote
     */
    public Remote() {             
        initComponents();
    }
    
    // Sets the specified command to the specified slot
    public static void setCommand(int slot, Command c) {
        switch (slot) {
            case 1:  slot1 = c;
                     break;
            case 2:  slot2 = c;
                     break;
            case 3:  slot3 = c;
                     break;
            default: System.out.println("Invalid slot");
                     break;
        }
    }
      
    // Executes the given command
    public static void execCommand(Command c) {
        c.execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCat = new javax.swing.JButton();
        jButtonLight = new javax.swing.JButton();
        jButtonDoor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaOutput = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonCat.setText("Toggle Cat");
        jButtonCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCatActionPerformed(evt);
            }
        });

        jButtonLight.setText("Lightswitch");
        jButtonLight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLightActionPerformed(evt);
            }
        });

        jButtonDoor.setText("Garage Door");
        jButtonDoor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoorActionPerformed(evt);
            }
        });

        jLabel1.setText("Remote Controller:");

        jTextAreaOutput.setColumns(20);
        jTextAreaOutput.setRows(5);
        jScrollPane1.setViewportView(jTextAreaOutput);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCat)
                    .addComponent(jButtonLight)
                    .addComponent(jLabel1)
                    .addComponent(jButtonDoor))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCat)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLight)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDoor)
                        .addGap(0, 78, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCatActionPerformed
        Remote.execCommand(slot1);
    }//GEN-LAST:event_jButtonCatActionPerformed

    private void jButtonLightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLightActionPerformed
        Remote.execCommand(slot2);
    }//GEN-LAST:event_jButtonLightActionPerformed

    private void jButtonDoorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDoorActionPerformed
        Remote.execCommand(slot3);
    }//GEN-LAST:event_jButtonDoorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        // Creating the objects that can be "commanded"
        Cat c = new Cat();
        Light l = new Light();
        GarageDoor gd = new GarageDoor();
        
        // Creating the commands for the objects
        Command catActivate = new CatCommand(c);
        Command lightOn = new LightCommand(l);
        Command doorOpen = new GarageDoorCommand(gd);
        
        /* Set the system default look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
             javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());

        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Remote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Remote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Remote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Remote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Remote().setVisible(true);
            }
        });
    
        // Setting the commands to the three slots on our remote
        Remote.setCommand(1, catActivate);
        Remote.setCommand(2, lightOn);
        Remote.setCommand(3, doorOpen);
    }

    public static void setTextAreaOutput(String t) {
        jTextAreaOutput.append(t + "\n");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCat;
    private javax.swing.JButton jButtonDoor;
    private javax.swing.JButton jButtonLight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextArea jTextAreaOutput;
    // End of variables declaration//GEN-END:variables
}
